version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=1234

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"