bind_addr = ":8080"

[store]
db_host = "db"
db_port = "5432"
db_name = "postgres"
db_user = "postgres"
db_password = "1234"
#database_url = "host=db port=5432 user=postgres password=1234 dbname=postgres sslmode=disable"